import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Head from "next/head";
import Link from "next/link";
import ReactMarkdown from "react-markdown";


const PatentPage = () => {
    const router = useRouter();
    const { slug } = router.query;
    const [patentItem, setPatentItem] = useState(null);

    useEffect(() => {
        const fetchPatentItem = async () => {
            try {
                const response = await fetch(`http://localhost:1337/api/patent-items?populate=*&urlSlug=${slug}`);
                const data = await response.json();
                console.log('API response:', data);
                if (data && data.data && data.data.length > 0) {
                    const matchingItem = data.data.find(item => item.attributes.urlSlug === slug);
                    setPatentItem(matchingItem || null);
                } else {
                    setPatentItem(null);
                }
            } catch (error) {
                console.error('Error fetching patent item:', error);
                setPatentItem(null);
            }
        };

        if (slug) {
            fetchPatentItem();
        }
    }, [slug]);

    if (!patentItem) {
        return <div>Loading...</div>;
    }

    const getFullImageUrl = (url) => {
        return `http://localhost:1337${url}`;
    };

    console.log('patentItem:', patentItem);

    return (
        <div>
            {/*<p>{patentItem.attributes.ShortDescription}</p>*/}
            {/* Render the rest of the patent item details */}


            <Head>
                <title>Sikander - DEV MVP</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>


                <div className="patent-container">

                    <header className="patent-header">
                        <div>
                            <button className="menu-button" tabIndex={0}>
                                <img src="/images/menu-but.png"/>
                                <span className="mobile-menu-block">
                              <a href="/" className="menu-item">Our Patents</a>
                              <a href="/" className="menu-item">Crafts</a>
                              <a href="/" className="menu-item">Stories</a>
                              <a href="/" className="menu-item">Crafters</a>
                              <a href="/" className="menu-item">Contacts</a>
                              <a href="/" className="book-link">Book Your FREE Call</a>
                          </span>
                            </button>
                            <Link href={"/"} className="header-logo">
                                <img src="/images/logo.png"/>
                            </Link>
                        </div>
                        <div className="patent-content">
                            <h1>{patentItem.attributes.Title}</h1>
                        </div>
                    </header>

                    <div className="patent-content">
                        <div className="left-block">
                            <div className="title-block">
                                <h2>{patentItem.attributes.Title}</h2>
                            </div>
                            <div className="text-cont" id="bord">
                                <h3>Invention</h3>
                                <ReactMarkdown>
                                    {patentItem.attributes.MainDescription}
                                </ReactMarkdown>
                                {/*<p>{patentItem.attributes.MainDescription}</p>*/}
                            </div>
                            <div className="text-cont">
                                <h3>Patent Features</h3>
                                <div className="text-mark">
                                    <ReactMarkdown>
                                        {patentItem.attributes.MainDescription2}
                                    </ReactMarkdown>
                                </div>
                                {/*<p>{patentItem.attributes.MainDescription2}</p>*/}
                            </div>

                            <div className="buttons-cont">
                                <a href="#1" className="link-button">
                                    annotation
                                </a>
                                <a href="#2" className="link-button">
                                    article
                                </a>
                                <a href="#3" className="link-button">
                                    FIGURES
                                </a>
                                <a href="#4" className="link-button sp-link">
                                    claims
                                </a>

                            </div>
                        </div>

                        {/*<div className="right-block">*/}
                            {/*<div id="1" className="img-container">*/}
                            {/*    <img src="/images/ex2.png"/>*/}
                            {/*</div>*/}
                            {/*<div id="2" className="img-container">*/}
                            {/*    <img src="/images/ex1.png"/>*/}
                            {/*</div>*/}
                            {/*<div id="3" className="img-container">*/}
                            {/*    <img src="/images/patent-base.png"/>*/}
                            {/*</div>*/}
                            {/*<div id="4" className="img-container">*/}
                            {/*    <img src="/images/ex2.png"/>*/}
                            {/*</div>*/}
                            {/*<div id="5" className="img-container">*/}
                            {/*    <img src="/images/patent-base.png"/>*/}
                            {/*</div>*/}
                        {/*</div>*/}


                        {patentItem.attributes.PatentImages?.data && (
                            <div className="right-block">
                                {patentItem.attributes.PatentImages.data.map((image) => (
                                    <div className="img-container" key={image.id}>
                                        <img
                                            src={getFullImageUrl(image.attributes.url)}
                                            alt={`Patent Image ${image.id}`}
                                        />
                                    </div>
                                ))}
                            </div>
                        )}

                        <div className="mobile-footer">
                            <img src="/images/line.png"/>
                            <a href="#" className="book-call">
                                Book Your Free Call
                            </a>
                        </div>

                    </div>

                </div>



            </main>

        </div>
    );
};

export default PatentPage;
